#application: duriezre
runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  max_instances: 1

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)
  secure: always
  redirect_http_response_code: 301

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json