#application: duriezre
runtime: python37
automatic_scaling:
  max_instances: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
